# Generated by Django 5.0.7 on 2024-07-28 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_article_dislikes_remove_article_likes_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
