# Generated by Django 5.0.7 on 2024-07-28 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='featured_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='user_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
