# Generated by Django 5.0.7 on 2024-07-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_featured_image_article_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bookmarks',
        ),
    ]
