# Generated by Django 5.0.7 on 2024-07-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_article_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('article', 'Articles'), ('diy', 'DIY Project')], default='article', max_length=20),
        ),
    ]
