# Generated by Django 5.0.7 on 2024-07-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
