# Generated by Django 5.0.7 on 2024-08-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_articleview'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articleview',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articleview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.article'),
        ),
    ]
