# Generated by Django 5.0.7 on 2024-08-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_articleview_referrer_articleview_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='frameworks',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='posts.framework'),
        ),
    ]
