# Generated by Django 5.0.7 on 2024-08-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_article_frameworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='frameworks',
            field=models.ManyToManyField(blank=True, related_name='articles', to='posts.framework'),
        ),
    ]
