# Generated by Django 5.0.7 on 2024-08-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_article_frameworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='articles/files/'),
        ),
    ]
