# Generated by Django 5.0.7 on 2024-08-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_article_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
        migrations.AddField(
            model_name='article',
            name='file_url',
            field=models.URLField(blank=True, help_text='Paste the direct download link for the project file.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste the link to the YouTube video.', null=True),
        ),
    ]
