# Generated by Django 5.0.7 on 2024-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
