# Generated by Django 5.0.7 on 2024-07-29 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_bulkemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkemail',
            name='site_settings',
        ),
    ]
