# Generated by Django 5.0.7 on 2024-08-18 09:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('section_id', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, help_text='What do you do... ?', max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images')),
                ('cover_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='cover_images')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='article_bookmark', to='posts.article')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
