# Generated by Django 5.0.7 on 2024-07-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='cover_images'),
        ),
    ]
